version: '3'

services:
    link:
        image: basip/link:latest
        container_name: link
        restart: always
        ports:
            - "80:80"
            - "6001:6001"
            - "5060:5060/udp"
            - "5060:5060/tcp"
            - "5080:5080/udp"
            - "5080:5080/tcp"
            - "5066:5066"
            - "7443:7443"
            - "8021:8021"
            - "64535-65300:64535-65300/udp"
        volumes:
            - app-data:/var/lib/mysql
            - system-logs:/var/log
            - app-storage:/share/storage
volumes:
  app-data:
  system-logs:
  app-storage:
